name: holdem
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: zanuka <email@example.com>

environment:
  sdk: '2.1.1'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
